### ISSUE TITLE
wordpress

### ISSUE THREAD

**Issue by julian-gamboa-ensino** [julian-gamboa-ensino/curso-php-chile#9]
# Passos básicos:

Um setup básico pode ser este **docker-compose.yml** com:
+ wordpress
+ phpmyadmin

```
version: '3.1'

services:

  wordpress:
    image: wordpress    
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - ./worpress:/var/www/html

  db:
    image: mysql:latest
    
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ./db:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: meu-phpmyadmin    
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: minhasenha
    ports:
      - "8081:80"      
```
